server:
  port: 80

spring:
  application:
    name: consumer-dept-feign

eureka:
  instance:
    instance-id: consumer-dept-feign80
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: "http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/"