server:
  port: 8001

mybatis:
  type-aliases-package: com.luxiaobu.springcloud.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  application:
    name: provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.3.17:3306/DB-01?serverTimezone=GMT%2B8&characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: 125567

eureka:
  instance:
    instance-id: provider-hystrix-dept8001
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: "http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/"

